name: Unit Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.5
        with:
          environments: test
          frozen: false
      - name: Run tests
        run: pixi run -e test pytest -vsl -p no:cov .