name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        # Simplificamos para probar primero en Ubuntu, que es el más rápido
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          # Quitamos la versión fija para que use la última disponible
          environments: test
          frozen: false

      - name: Run tests
        run: pixi run -e test test